import type { Player, Game } from "./types";

export const GAMES: Game[] = [
  {
    id: "g1",
    homeTeam: "Boston Celtics",
    awayTeam: "Miami Heat",
    homeColor: "#007A33",
    awayColor: "#98002E",
    time: "7:30 PM ET",
    spread: -3.5,
  },
  {
    id: "g2",
    homeTeam: "LA Lakers",
    awayTeam: "Golden State Warriors",
    homeColor: "#552583",
    awayColor: "#1D428A",
    time: "10:00 PM ET",
    spread: 1.5,
  },
  {
    id: "g3",
    homeTeam: "Denver Nuggets",
    awayTeam: "Phoenix Suns",
    homeColor: "#0E2240",
    awayColor: "#1D1160",
    time: "9:00 PM ET",
    spread: -5.0,
  },
];

export const PLAYERS: Player[] = [
  {
    id: "p1",
    name: "Jayson Tatum",
    team: "Boston Celtics",
    teamColor: "#007A33",
    position: "SF",
    props: {
      points: { line: 27.5, avgOdds: -115 },
      rebounds: { line: 8.5, avgOdds: -110 },
      assists: { line: 4.5, avgOdds: -105 },
      threes: { line: 2.5, avgOdds: -120 },
      steals: { line: 0.5, avgOdds: -130 },
      blocks: { line: 0.5, avgOdds: -115 },
    },
  },
  {
    id: "p2",
    name: "Jaylen Brown",
    team: "Boston Celtics",
    teamColor: "#007A33",
    position: "SG",
    props: {
      points: { line: 22.5, avgOdds: -110 },
      rebounds: { line: 5.5, avgOdds: -105 },
      assists: { line: 3.5, avgOdds: -110 },
      threes: { line: 2.5, avgOdds: -115 },
      steals: { line: 0.5, avgOdds: -120 },
      blocks: { line: 0.5, avgOdds: -110 },
    },
  },
  {
    id: "p3",
    name: "Jimmy Butler",
    team: "Miami Heat",
    teamColor: "#98002E",
    position: "SF",
    props: {
      points: { line: 20.5, avgOdds: -110 },
      rebounds: { line: 5.5, avgOdds: -105 },
      assists: { line: 4.5, avgOdds: -115 },
      threes: { line: 1.5, avgOdds: -120 },
      steals: { line: 1.5, avgOdds: -110 },
      blocks: { line: 0.5, avgOdds: -105 },
    },
  },
  {
    id: "p4",
    name: "Bam Adebayo",
    team: "Miami Heat",
    teamColor: "#98002E",
    position: "C",
    props: {
      points: { line: 18.5, avgOdds: -115 },
      rebounds: { line: 9.5, avgOdds: -110 },
      assists: { line: 3.5, avgOdds: -105 },
      threes: { line: 0.5, avgOdds: -130 },
      steals: { line: 1.5, avgOdds: -115 },
      blocks: { line: 1.5, avgOdds: -110 },
    },
  },
  {
    id: "p5",
    name: "LeBron James",
    team: "LA Lakers",
    teamColor: "#552583",
    position: "SF",
    props: {
      points: { line: 25.5, avgOdds: -115 },
      rebounds: { line: 7.5, avgOdds: -110 },
      assists: { line: 7.5, avgOdds: -115 },
      threes: { line: 1.5, avgOdds: -110 },
      steals: { line: 1.5, avgOdds: -120 },
      blocks: { line: 0.5, avgOdds: -115 },
    },
  },
  {
    id: "p6",
    name: "Anthony Davis",
    team: "LA Lakers",
    teamColor: "#552583",
    position: "C",
    props: {
      points: { line: 26.5, avgOdds: -115 },
      rebounds: { line: 12.5, avgOdds: -110 },
      assists: { line: 2.5, avgOdds: -105 },
      threes: { line: 0.5, avgOdds: -140 },
      steals: { line: 1.5, avgOdds: -110 },
      blocks: { line: 2.5, avgOdds: -115 },
    },
  },
  {
    id: "p7",
    name: "Stephen Curry",
    team: "Golden State Warriors",
    teamColor: "#1D428A",
    position: "PG",
    props: {
      points: { line: 28.5, avgOdds: -115 },
      rebounds: { line: 5.5, avgOdds: -110 },
      assists: { line: 5.5, avgOdds: -110 },
      threes: { line: 4.5, avgOdds: -120 },
      steals: { line: 0.5, avgOdds: -115 },
      blocks: { line: 0.5, avgOdds: -105 },
    },
  },
  {
    id: "p8",
    name: "Nikola Jokic",
    team: "Denver Nuggets",
    teamColor: "#0E2240",
    position: "C",
    props: {
      points: { line: 26.5, avgOdds: -110 },
      rebounds: { line: 12.5, avgOdds: -115 },
      assists: { line: 8.5, avgOdds: -110 },
      threes: { line: 0.5, avgOdds: -130 },
      steals: { line: 1.5, avgOdds: -110 },
      blocks: { line: 0.5, avgOdds: -105 },
    },
  },
];
